services:
  - type: web
    name: mpt-admission-bot
    runtime: docker
    plan: free
    branch: master
    healthCheckPath: /
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        value: "6360613956"
      - key: DATA_DIR
        value: data
      - key: TELEGRAM_PROXY_URL
        value: ""
      - key: BOT_MODE
        value: webhook
      - key: WEBHOOK_HOSTNAME
        fromService:
          type: web
          name: mpt-admission-bot
          envVarKey: RENDER_EXTERNAL_HOSTNAME
      - key: WEBHOOK_PATH
        value: /webhook
      - key: WEBHOOK_SECRET
        generateValue: true
